const express = require('express');
const router = express.Router();
const User = require('../models/User');
const Activity = require('../models/Activity');
const TimeLog = require('../models/TimeLog');
const Goal = require('../models/Goal');
const Task = require('../models/Task');
const Leave = require('../models/Leave');
const { authMiddleware } = require('../middleware/auth');
const { sanitizeActivities, aggregateByDomain } = require('../utils/privacy');

const { getWorkingDays } = require('../utils/attendance');
const PDFDocument = require('pdfkit');
const axios = require('axios');
const { formatDuration } = require('../utils/timeFormat');

// ─── Design Tokens ────────────────────────────────────────────────────────────
const GOLD   = '#FFCC00';
const BLACK  = '#000000';
const DARK   = '#111111';
const MID    = '#444444';
const LIGHT  = '#888888';
const RULE   = '#DDDDDD';
const BG_ALT = '#F7F7F7';
const GREEN  = '#2E7D32';
const RED    = '#C62828';
const AMBER  = '#F9A825';

const PAGE_W = 595;
const PAGE_H = 842;
const L      = 45;
const R      = 550;
const COL_W  = R - L;

// ─── Helpers ──────────────────────────────────────────────────────────────────

const drawSectionHeader = (doc, label, y) => {
  doc.rect(L, y, COL_W, 22).fill(DARK);
  doc.fontSize(9).font('Helvetica-Bold').fillColor(GOLD)
    .text(label.toUpperCase(), L + 10, y + 6, { width: COL_W - 20, lineBreak: false });
  return y + 28;
};

const rule = (doc, y, color = RULE) => {
  doc.rect(L, y, COL_W, 0.5).fill(color);
  return y + 8;
};

const drawKPI = (doc, label, value, x, y, w, accent) => {
  w = w || 110; accent = accent || GOLD;
  doc.rect(x, y, w, 72).fill('#FAFAFA');
  doc.rect(x, y + 70, w, 2).fill(accent);
  doc.rect(x, y, w, 72).stroke(RULE);
  doc.fontSize(7).font('Helvetica-Bold').fillColor(LIGHT)
    .text(label, x + 8, y + 10, { width: w - 16, lineBreak: false });
  doc.fontSize(22).font('Helvetica-Bold').fillColor(DARK)
    .text(value, x + 8, y + 26, { width: w - 16, lineBreak: false });
};

const drawCover = async (doc, title, subtitle, detail) => {
  doc.rect(0, 0, PAGE_W, 8).fill(GOLD);
  doc.rect(0, 8, PAGE_W, 90).fill(DARK);

  // Logo
  doc.rect(L, 18, 60, 62).fill('#222222');
  doc.fontSize(7).font('Helvetica-Bold').fillColor(GOLD).text('MTN', L + 15, 46, { lineBreak: false });
  try {
    const response = await axios.get('https://logonoid.com/images/mtn-logo.jpg', { responseType: 'arraybuffer' });
    doc.image(Buffer.from(response.data, 'binary'), L, 18, { width: 60, height: 62 });
  } catch (_) {}

  // Company name ABOVE the report title (Prominent branding)
  doc.fontSize(24).font('Helvetica-Bold').fillColor(GOLD)
    .text('MTN', L + 72, 20, { width: COL_W - 72, lineBreak: false });
  doc.fontSize(10).font('Helvetica-Bold').fillColor(GOLD)
    .text('RWANDA', L + 128, 31, { width: COL_W - 72, lineBreak: false });

  // Report title below company name
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#FFFFFF')
    .text(title, L + 72, 48, { width: COL_W - 72, lineBreak: false });
    
  doc.fontSize(8).font('Helvetica').fillColor('#BBBBBB')
    .text(subtitle, L + 72, 66, { width: COL_W - 72, lineBreak: false });
  doc.fontSize(7).font('Helvetica').fillColor('#888888')
    .text(detail, L + 72, 78, { width: COL_W - 72, lineBreak: false });

  doc.rect(0, 98, PAGE_W, 3).fill(GOLD);
};

const drawFooter = (doc, generatedOn) => {
  doc.rect(0, PAGE_H - 28, PAGE_W, 28).fill(DARK);
  doc.fontSize(7).font('Helvetica').fillColor('#888888')
    .text('ProTrackAI — MTN Rwanda Corporate Performance Management', L, PAGE_H - 18, { align: 'center', width: COL_W });
  doc.fillColor(LIGHT)
    .text('Generated: ' + generatedOn, L, PAGE_H - 18, { align: 'right', width: COL_W });
};

// ─ Duration Formatter ─────────────────────────────────────────────────────────

// ─ Closing Signature Page ─────────────────────────────────────────────────────
const drawSignaturePage = (doc, requesterName, generatedOn) => {
  doc.addPage();
  // Full divider line near top
  doc.rect(L, 80, COL_W, 0.5).fill(RULE);

  // Left: Generated by
  doc.fontSize(9).font('Helvetica').fillColor(LIGHT).text('Generated by', L, 100, { lineBreak: false });
  doc.fontSize(13).font('Helvetica-Bold').fillColor(DARK).text(requesterName, L, 116, { lineBreak: false });
  doc.fontSize(8.5).font('Helvetica').fillColor(LIGHT).text('Date: ' + generatedOn.toLocaleDateString('en-GB'), L, 136, { lineBreak: false });

  drawFooter(doc, generatedOn.toLocaleString());
};

const infoRow = (doc, label, value, x, y, valColor) => {
  valColor = valColor || MID;
  doc.fontSize(8).font('Helvetica-Bold').fillColor(LIGHT).text(label, x, y, { lineBreak: false });
  doc.fontSize(8).font('Helvetica').fillColor(valColor).text(value, x + 90, y, { lineBreak: false });
};

router.use(authMiddleware);

// ════════════════════════════════════════════════════════════════════════════
//  GET /api/reports  (JSON stats)
// ════════════════════════════════════════════════════════════════════════════


// ─── Formatting Helpers ───────────────────────────────────────────────────────

const drawTable = (doc, headers, rows, config, y) => {
  const { colW, xStart = L, rowH = 18, fontSize = 7.5 } = config;
  
  // Header
  doc.rect(xStart, y, COL_W, rowH).fill('#222222');
  doc.fontSize(fontSize).font('Helvetica-Bold').fillColor(GOLD);
  headers.forEach((h, i) => {
    doc.text(h.toUpperCase(), xStart + colW[i] + 4, y + 5, { lineBreak: false });
  });
  y += rowH + 2;

  // Rows
  rows.forEach((row, ri) => {
    if (ri % 2 === 1) doc.rect(xStart, y - 1, COL_W, rowH).fill('#F9F9F9');
    doc.fontSize(fontSize).font('Helvetica').fillColor('#333333');
    
    row.forEach((cell, ci) => {
      // Handle colors if cell is an object
      const val = typeof cell === 'object' ? cell.text : cell;
      const color = typeof cell === 'object' ? cell.color : '#333333';
      const isBold = typeof cell === 'object' ? cell.bold : false;

      doc.fillColor(color).font(isBold ? 'Helvetica-Bold' : (ci === 0 ? 'Helvetica-Bold' : 'Helvetica'))
         .text(val, xStart + colW[ci] + 4, y + 4, { lineBreak: false });
    });
    y += rowH;
  });
  
  return y + 10;
};

const drawSummaryHeader = (doc, data, y) => {
    doc.rect(L, y, COL_W, 28).fill(DARK);
    doc.rect(L, y, 3, 28).fill(GOLD);
    
    const count = data.length;
    const unitW = COL_W / count;
    
    data.forEach((item, i) => {
        doc.fontSize(6).font('Helvetica-Bold').fillColor(LIGHT).text(item.label.toUpperCase(), L + (i * unitW) + 10, y + 6, { lineBreak: false });
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#FFFFFF').text(item.value, L + (i * unitW) + 10, y + 14, { lineBreak: false });
    });
    return y + 36;
};

router.use(authMiddleware);

// ════════════════════════════════════════════════════════════════════════════
//  GET /api/reports  (JSON stats)
// ════════════════════════════════════════════════════════════════════════════
router.get('/', async (req, res) => {
  console.log(`[API] GET /api/reports - User: ${req.query.userId}, Period: ${req.query.period}`);
  try {
    const { userId, period = 'month', start, end } = req.query;
    if (!userId) return res.status(400).json({ error: 'Missing userId param' });

    const now = new Date();
    let startDate = new Date(now), endDate = new Date();

    if (period === 'custom' && start && end) {
      startDate = new Date(start);
      endDate = new Date(end);
    } else {
      if (period === 'today') startDate.setHours(0, 0, 0, 0);
      else if (period === 'week') startDate.setDate(now.getDate() - 7);
      else if (period === 'quarter') startDate.setMonth(now.getMonth() - 3);
      else if (period === 'month') startDate.setMonth(now.getMonth() - 1);
    }

    const activityMatch = { userId: new RegExp(`^${userId}$`, 'i'), timestamp: { $gte: startDate, $lte: endDate } };

    const stats = await Activity.aggregate([
      { $match: activityMatch },
      { $group: { _id: '$classified', totalDuration: { $sum: '$duration' } } }
    ]);

    const totalTime = stats.reduce((s, a) => s + (a.totalDuration || 0), 0);
    const productiveTime = stats.find(a => a._id === 'productive')?.totalDuration || 0;
    const neutralTime = stats.find(a => ['neutral', 'unknown', 'review_required'].includes(a._id))?.totalDuration || 0;
    const nonProductiveTime = stats.find(a => a._id === 'non-productive')?.totalDuration || 0;
    const efficiency = totalTime > 0 ? Math.round((productiveTime / totalTime) * 100) + '%' : '0%';

    const domainAgg = await Activity.aggregate([
      { $match: activityMatch },
      { $group: { _id: '$appName', duration: { $sum: '$duration' }, classified: { $first: '$classified' } } },
      { $sort: { duration: -1 } },
      { $limit: 15 }
    ]);

    const recentItems = await Activity.find(activityMatch).sort({ timestamp: -1 }).limit(100);
    const sanitized = sanitizeActivities(recentItems, 'employee');

    console.log(`[API] GET /api/reports - Success. Efficiency: ${efficiency}, Recent: ${sanitized.length}`);
    res.json({
      efficiency, totalTime, productiveTime, neutralTime, nonProductiveTime,
      recentActivities: sanitized,
      domainBreakdown: domainAgg.map(d => ({ name: d._id || 'Unknown', duration: d.duration, classified: d.classified })),
      period: { start: startDate, end: endDate }
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ════════════════════════════════════════════════════════════════════════════
//  GET /api/reports/pdf  (Employee PDF)
// ════════════════════════════════════════════════════════════════════════════
router.get('/pdf', async (req, res) => {
  try {
    const { userId, period = 'month', reportType = 'all' } = req.query;
    if (!userId) return res.status(400).json({ error: 'Missing userId param' });

    const user = await User.findOne({ id: userId });
    if (!user) return res.status(404).json({ error: 'User not found' });

    const requester = await User.findOne({ id: req.user.id });
    const requesterName = requester ? requester.name : (req.user.name || 'Authorized Personnel');

    const now = new Date();
    const endDate = new Date();
    let startDate;
    if (req.query.start && req.query.end) {
      startDate = new Date(req.query.start);
      endDate.setTime(new Date(req.query.end).setHours(23, 59, 59, 999));
    } else if (period === 'week') {
      startDate = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    } else if (period === 'month') {
      startDate = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    } else {
      startDate = new Date(now); startDate.setHours(0, 0, 0, 0);
    }

    const activities = await Activity.find({ userId, timestamp: { $gte: startDate, $lte: endDate } }).sort({ timestamp: -1 });
    const timeLogs   = await TimeLog.find({ userId, timestamp: { $gte: startDate, $lte: endDate } });
    
    // Header for PDF
    const doc = new PDFDocument({ margin: 0, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Audit_${user.name.replace(/\s+/g, '_')}_${period}_${reportType}.pdf`);
    doc.pipe(res);

    const title = reportType === 'violation' ? 'POLICY VIOLATIONS RECORD' : reportType.toUpperCase() + ' PERFORMANCE RECORD';
    let periodStr = period.toUpperCase();
    if (period === 'custom') {
      periodStr = `CUSTOM (${startDate.toISOString().split('T')[0]} to ${endDate.toISOString().split('T')[0]})`;
    }
    await drawCover(doc, title, `Employee: ${user.name} (${userId})`, `Period: ${periodStr} Audit Document`);

    let y = 110;

    // ──────────────────────────────────────────────────────────────────────────
    // ATTENDANCE REALM
    // ──────────────────────────────────────────────────────────────────────────
    if (reportType === 'all' || reportType === 'attendance') {
        const checkIns = timeLogs.filter(l => l.type === 'check-in');
        const present = checkIns.filter(l => l.status === 'present').length;
        const lates = checkIns.filter(l => l.status === 'late').length;

        y = drawSectionHeader(doc, 'Attendance Audit Summary', y);
        y = drawSummaryHeader(doc, [
            { label: 'Total Logs', value: String(checkIns.length) },
            { label: 'On-Time', value: String(present) },
            { label: 'Late Flags', value: String(lates) },
            { label: 'Reliability', value: (checkIns.length > 0 ? Math.round((present / checkIns.length) * 100) : 0) + '%' }
        ], y);

        const auditRows = await Promise.all(checkIns.map(async (l, i) => {
            const dayStart = new Date(l.timestamp); dayStart.setHours(0,0,0,0);
            const dayEnd = new Date(l.timestamp); dayEnd.setHours(23,59,59,999);
            const firstTask = await Activity.findOne({ userId, timestamp: { $gte: dayStart, $lte: dayEnd } }).sort({ timestamp: 1 });
            const gap = firstTask ? Math.round((firstTask.timestamp - l.timestamp) / 60000) : 0;
            return [
                '#' + (i + 1),
                l.timestamp.toLocaleDateString('en-GB'),
                l.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
                firstTask ? firstTask.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—',
                gap > 0 ? gap + 'm' : '—',
                { text: (l.status || 'present').toUpperCase(), color: l.status === 'late' ? AMBER : GREEN, bold: true }
            ];
        }));

        const maxRows = period === 'today' ? 1 : period === 'week' ? 7 : 31;
        y = drawTable(doc, 
            ['SN', 'Date', 'Clock In', 'First Task', 'Gap', 'Status'],
            auditRows.slice(0, maxRows), 
            { colW: [0, 30, 110, 200, 290, 380] },
            y
        );
    }

    // ──────────────────────────────────────────────────────────────────────────
    // VIOLATIONS REALM (Individual)
    // ──────────────────────────────────────────────────────────────────────────
    if (reportType === 'all' || reportType === 'violation') {
        const lateLogs = timeLogs.filter(l => l.type === 'check-in' && l.status === 'late');
        const totalDur = activities.reduce((s, a) => s + (a.duration || 0), 0);
        const prodDur = activities.filter(a => a.classified === 'productive').reduce((s, a) => s + (a.duration || 0), 0);
        const ratio = totalDur > 0 ? Math.round((prodDur / totalDur) * 100) : 0;
        
        if (reportType === 'violation' || lateLogs.length > 2 || ratio < 60) {
            y = drawSectionHeader(doc, 'Policy Violations & Warnings', y);
            
            const infractions = [];
            if (lateLogs.length > 2) infractions.push(`Chronic Tardiness: Arrived late ${lateLogs.length} times in this period.`);
            if (ratio > 0 && ratio < 60) infractions.push(`Low Productivity: Efficiency ratio is ${ratio}%. Well below the 70% minimum threshold.`);
            
            if (infractions.length === 0 && reportType === 'violation') {
                infractions.push('No obvious systemic violations detected in this period.');
            }

            y = drawSummaryHeader(doc, infractions.map((inf, idx) => ({ label: `Warning ${idx + 1}`, value: inf })), y);
            
            const nprdActivities = aggregateByDomain(activities.filter(a => a.classified === 'non-productive'));
            const violatorRows = nprdActivities.slice(0, 5).map((d, i) => [
                '#' + (i + 1),
                d.domain,
                'UNAUTHORIZED/DISTRACTION',
                formatDuration(d.totalDuration),
                Math.round(d.percent) + '%'
            ]);

            if (violatorRows.length > 0) {
                y = drawTable(doc,
                    ['SN', 'Non-Productive Domain', 'Flag Type', 'Time Lost', 'Share %'],
                    violatorRows,
                    { colW: [0, 30, 240, 350, 440] },
                    y
                );
            }
        }
    }

    // ──────────────────────────────────────────────────────────────────────────
    // PRODUCTIVITY REALM
    // ──────────────────────────────────────────────────────────────────────────
    if (reportType === 'all' || reportType === 'productivity') {
        const totalDur = activities.reduce((s, a) => s + (a.duration || 0), 0);
        const prodDur = activities.filter(a => a.classified === 'productive').reduce((s, a) => s + (a.duration || 0), 0);
        const ratio = totalDur > 0 ? Math.round((prodDur / totalDur) * 100) : 0;

        y = drawSectionHeader(doc, 'Productivity Alignment & Efficiency', y);
        y = drawSummaryHeader(doc, [
            { label: 'Total Logged', value: formatDuration(totalDur) },
            { label: 'Productive', value: formatDuration(prodDur) },
            { label: 'Efficiency', value: ratio + '%' },
            { label: 'Status', value: ratio >= 70 ? 'OPTIMAL' : 'RECOVERY' }
        ], y);

        const domainStats = aggregateByDomain(activities);
        const toolRows = domainStats.slice(0, 10).map((d, i) => [
            '#' + (i + 1),
            d.domain,
            { text: (d.classified || 'Neutral').toUpperCase(), color: d.classified === 'productive' ? GREEN : d.classified === 'non-productive' ? RED : LIGHT },
            formatDuration(d.totalDuration),
            Math.round(d.percent) + '%'
        ]);

        y = drawTable(doc,
            ['SN', 'Application / Domain', 'Classification', 'Focus Time', 'Share %'],
            toolRows,
            { colW: [0, 30, 240, 350, 440] },
            y
        );
    }

    drawFooter(doc, now.toLocaleString());
    drawSignaturePage(doc, requesterName, now);
    doc.end();

  } catch (err) {
    console.error('Individual PDF error:', err);
    res.status(500).json({ error: err.message });
  }
});

// ════════════════════════════════════════════════════════════════════════════
//  GET /api/reports/team-pdf  (Supervisor Team PDF)
// ════════════════════════════════════════════════════════════════════════════
router.get('/team-pdf', async (req, res) => {
  try {
    const { period = 'month', reportType = 'all' } = req.query;
    const supervisor = await User.findOne({ id: req.user.id });
    if (supervisor.role !== 'supervisor') return res.status(403).json({ error: 'Supervisor perms required' });

    const team = supervisor.team;
    const members = await User.find({ team: { $regex: new RegExp('^' + team + '$', 'i') }, role: 'employee' }).select('id name');
    const memberIds = members.map(m => m.id);

    const now = new Date();
    let endDate = new Date();
    let startDate = new Date();
    if (period === 'custom' && req.query.start && req.query.end) {
      startDate = new Date(req.query.start);
      endDate.setTime(new Date(req.query.end).setHours(23, 59, 59, 999));
    } else if (period === 'week') {
      startDate.setDate(now.getDate() - 7);
    } else if (period === 'month') {
      startDate.setTime(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    } else {
      startDate.setHours(0, 0, 0, 0);
    }

    const activities = await Activity.find({ userId: { $in: memberIds }, timestamp: { $gte: startDate, $lte: endDate } });
    const logs = await TimeLog.find({ userId: { $in: memberIds }, timestamp: { $gte: startDate, $lte: endDate }, type: 'check-in' });

    const doc = new PDFDocument({ margin: 0, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    const typeLabel = reportType === 'attendance' ? 'Attendance' : reportType === 'productivity' ? 'Productivity' : 'Full';
    const dateStr = now.toISOString().split('T')[0];
    res.setHeader('Content-Disposition', `attachment; filename=MTN_Team_${typeLabel}_Audit_${team}_${period}_${dateStr}.pdf`);
    doc.pipe(res);

    const coverTitle = reportType === 'attendance' ? 'TEAM ATTENDANCE AUDIT' : reportType === 'productivity' ? 'TEAM PRODUCTIVITY AUDIT' : reportType === 'violation' ? 'TEAM VIOLATIONS REPORT' : 'TEAM OPERATIONAL AUDIT';
    
    let periodStr = period.toUpperCase();
    if (period === 'custom') {
      periodStr = `CUSTOM (${startDate.toISOString().split('T')[0]} to ${endDate.toISOString().split('T')[0]})`;
    }
    
    await drawCover(doc, coverTitle, `Unit: ${team} | Supervisor: ${supervisor.name}`, `Period: ${periodStr} | Generated: ${dateStr}`);

    let y = 110;

    const teamTot = activities.reduce((s,a) => s + (a.duration || 0), 0);
    const teamPrd = activities.filter(a => a.classified === 'productive').reduce((s,a) => s + a.duration, 0);
    const teamEff = teamTot > 0 ? Math.round((teamPrd / teamTot) * 100) : 0;
    const teamAtt = logs.length > 0 ? Math.round((logs.filter(l => l.status === 'present').length / logs.length) * 100) : 0;
    const teamLate = logs.filter(l => l.status === 'late').length;

    // ── ATTENDANCE REPORT ──────────────────────────────────────────────────────
    if (reportType === 'all' || reportType === 'attendance') {
        y = drawSectionHeader(doc, 'Attendance Overview', y);
        y = drawSummaryHeader(doc, [
            { label: 'Team Size', value: String(members.length) },
            { label: 'Avg Attendance', value: teamAtt + '%' },
            { label: 'Late Flags', value: String(teamLate) },
            { label: 'Status', value: teamAtt >= 80 ? 'EXCELLENT' : 'REVIEW' }
        ], y);

        const attRows = members.map((m, i) => {
            const uL = logs.filter(l => l.userId === m.id);
            const present = uL.filter(l => l.status === 'present').length;
            const late = uL.filter(l => l.status === 'late').length;
            const att = uL.length > 0 ? Math.round((present / uL.length) * 100) : 0;
            return [
                '#' + (i + 1),
                m.name.length > 20 ? m.name.slice(0, 18) + '...' : m.name,
                String(uL.length),
                String(present),
                String(late),
                att + '%',
                { text: att >= 80 ? 'EXCELLENT' : att >= 60 ? 'REVIEW' : 'CRITICAL', color: att >= 80 ? GREEN : att >= 60 ? AMBER : RED, bold: true }
            ];
        });

        y = drawTable(doc,
            ['SN', 'Employee Name', 'Total Days', 'On-Time', 'Late', 'Rate %', 'Reliability'],
            attRows,
            { colW: [0, 30, 175, 250, 310, 370, 430] },
            y
        );
    }

    // ── PRODUCTIVITY REPORT ───────────────────────────────────────────────────
    if (reportType === 'all' || reportType === 'productivity') {
        y = drawSectionHeader(doc, 'Productivity Overview', y);
        y = drawSummaryHeader(doc, [
            { label: 'Team Size', value: String(members.length) },
            { label: 'Team Efficiency', value: teamEff + '%' },
            { label: 'Total Focus Time', value: formatDuration(teamPrd) },
            { label: 'Status', value: teamEff >= 70 ? 'OPTIMAL' : 'REVIEW' }
        ], y);

        const prodRows = members.map((m, i) => {
            const uA = activities.filter(a => a.userId === m.id);
            const tot = uA.reduce((s,a) => s + (a.duration || 0), 0);
            const prd = uA.filter(a => a.classified === 'productive').reduce((s,a) => s + (a.duration || 0), 0);
            const nprd = uA.filter(a => a.classified === 'non-productive').reduce((s,a) => s + (a.duration || 0), 0);
            const eff = tot > 0 ? Math.round((prd / tot) * 100) : 0;
            return [
                '#' + (i + 1),
                m.name.length > 18 ? m.name.slice(0, 16) + '...' : m.name,
                formatDuration(tot),
                formatDuration(prd),
                formatDuration(nprd),
                { text: eff + '%', color: eff >= 70 ? GREEN : eff >= 40 ? AMBER : RED, bold: true },
                { text: eff >= 70 ? 'OPTIMAL' : eff >= 40 ? 'REVIEW' : 'AT RISK', color: eff >= 70 ? GREEN : eff >= 40 ? AMBER : RED }
            ];
        });

        y = drawTable(doc,
            ['SN', 'Employee Name', 'Total Time', 'Productive', 'Non-Prod', 'Efficiency', 'Status'],
            prodRows,
            { colW: [0, 30, 175, 250, 320, 390, 450] },
            y
        );
    }

    // ── VIOLATIONS REPORT ─────────────────────────────────────────────────────
    if (reportType === 'violation') {
        const violatorRows = [];
        members.forEach((m, i) => {
            const uL = logs.filter(l => l.userId === m.id);
            const late = uL.filter(l => l.status === 'late').length;
            const uA = activities.filter(a => a.userId === m.id);
            const tot = uA.reduce((s,a) => s + (a.duration || 0), 0);
            const prd = uA.filter(a => a.classified === 'productive').reduce((s,a) => s + (a.duration || 0), 0);
            const eff = tot > 0 ? Math.round((prd / tot) * 100) : 0;
            
            // Criteria: More than 2 lates or efficiency less than 60%
            if (late > 2 || (tot > 3600 && eff < 60)) {
                let reason = [];
                if (late > 2) reason.push(`Chronic Late (${late}x)`);
                if (tot > 3600 && eff < 60) reason.push(`Low Prod (${eff}%)`);
                
                violatorRows.push([
                    '#' + (violatorRows.length + 1),
                    m.name.length > 20 ? m.name.slice(0, 18) + '...' : m.name,
                    String(late),
                    eff + '%',
                    reason.join(' | '),
                    { text: 'AT RISK', color: RED, bold: true }
                ]);
            }
        });

        y = drawSectionHeader(doc, 'System Violators Roster', y);
        y = drawSummaryHeader(doc, [
            { label: 'Total Audited', value: String(members.length) },
            { label: 'Violators Found', value: String(violatorRows.length) },
            { label: 'Compliance Level', value: members.length > 0 ? Math.round(((members.length - violatorRows.length) / members.length) * 100) + '%' : '0%' }
        ], y);

        if (violatorRows.length > 0) {
            y = drawTable(doc,
                ['SN', 'Employee Name', 'Late Flags', 'Efficiency', 'Primary Infraction', 'Status'],
                violatorRows,
                { colW: [0, 30, 175, 250, 320, 440] },
                y
            );
        } else {
            doc.fontSize(10).font('Helvetica-Bold').fillColor(DARK).text('No violations detected in this period.', L, y + 20);
            y += 40;
        }
    }

    drawFooter(doc, now.toLocaleString());
    drawSignaturePage(doc, supervisor.name, now);
    doc.end();

  } catch (err) {
    console.error('Team PDF error:', err);
    res.status(500).json({ error: err.message });
  }
});

// ════════════════════════════════════════════════════════════════════════════
//  GET /api/reports/hr-pdf  (HR Workforce PDF)
// ════════════════════════════════════════════════════════════════════════════
router.get('/hr-pdf', async (req, res) => {
  try {
    const { period = 'month', reportType = 'all', viewMode = 'dept' } = req.query;
    if (req.user.role !== 'hr') return res.status(403).json({ error: 'HR access required' });

    const hrUser = await User.findOne({ id: req.user.id });
    const now = new Date();
    let endDate = new Date();
    let startDate = new Date();
    if (period === 'custom' && req.query.start && req.query.end) {
      startDate = new Date(req.query.start);
      endDate.setTime(new Date(req.query.end).setHours(23, 59, 59, 999));
    } else if (period === 'week') {
      startDate.setDate(now.getDate() - 7);
    } else if (period === 'month') {
      startDate.setTime(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    } else {
      startDate.setHours(0, 0, 0, 0); // 'today'
    }

    const users = await User.find({ role: 'employee' }).select('id name dept team');
    const userIds = users.map(u => u.id);
    const activities = await Activity.find({ userId: { $in: userIds }, timestamp: { $gte: startDate, $lte: endDate } });
    const logs = await TimeLog.find({ userId: { $in: userIds }, timestamp: { $gte: startDate, $lte: endDate }, type: 'check-in' });

    const doc = new PDFDocument({ margin: 0, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    const hrDateStr = now.toISOString().split('T')[0];
    res.setHeader('Content-Disposition', `attachment; filename=MTN_Workforce_Audit_${viewMode.toUpperCase()}_${period}_${reportType}_${hrDateStr}.pdf`);
    doc.pipe(res);

    const titlePrefix = reportType === 'attendance' ? 'ATTENDANCE' : reportType === 'productivity' ? 'PRODUCTIVITY' : reportType === 'violation' ? 'VIOLATIONS' : 'WORKFORCE';
    let periodStr = period.toUpperCase();
    if (period === 'custom') {
      periodStr = `CUSTOM (${startDate.toISOString().split('T')[0]} to ${endDate.toISOString().split('T')[0]})`;
    }
    await drawCover(doc, `${titlePrefix} CAPACITY AUDIT`, `Organization-Wide ${viewMode === 'team' ? 'Team' : 'Departmental'} Analysis`, `Period: ${periodStr}`);

    let y = 110;

    // Organizational Overview
    const orgProd = activities.length > 0 ? Math.round((activities.filter(a => a.classified === 'productive').reduce((s,a) => s + a.duration, 0) / activities.reduce((s,a) => s + a.duration, 0)) * 100) : 0;
    const orgAtt = logs.length > 0 ? Math.round((logs.filter(l => l.status === 'present').length / logs.length) * 100) : 0;

    y = drawSectionHeader(doc, 'Global Performance Summary', y);
    y = drawSummaryHeader(doc, [
        { label: 'Total Staff', value: String(users.length) },
        { label: 'Avg Efficiency', value: orgProd + '%' },
        { label: 'Reliability', value: orgAtt + '%' },
        { label: 'Status', value: 'OPERATIONAL' }
    ], y);

    // Grouping Logic
    const groups = [...new Set(users.map(u => viewMode === 'team' ? u.team : u.dept).filter(Boolean))];
    const groupStats = groups.map((gName, i) => {
        const gUsers = users.filter(u => (viewMode === 'team' ? u.team : u.dept) === gName);
        const gIds = gUsers.map(u => u.id);
        const gActs = activities.filter(a => gIds.includes(a.userId));
        const gLogs = logs.filter(l => gIds.includes(l.userId));

        const tot = gActs.reduce((s,a) => s + (a.duration || 0), 0);
        const prd = gActs.filter(a => a.classified === 'productive').reduce((s,a) => s + (a.duration || 0), 0);
        const eff = tot > 0 ? Math.round((prd / tot) * 100) : 0;
        const att = gLogs.length > 0 ? Math.round((gLogs.filter(l => l.status === 'present').length / gLogs.length) * 100) : 0;

        if (reportType === 'attendance') {
            const lateCount = gLogs.filter(l => l.status === 'late').length;
            return [
                '#' + (i + 1),
                gName,
                att + '%',
                String(lateCount),
                { text: att >= 80 ? 'EXCELLENT' : 'REVIEW', color: att >= 80 ? GREEN : AMBER }
            ];
        } else if (reportType === 'productivity') {
            const focusHours = Math.round(prd / 3600);
            return [
                '#' + (i + 1),
                gName,
                eff + '%',
                formatDuration(prd),
                { text: eff >= 70 ? 'OPTIMAL' : 'RISK', color: eff >= 70 ? GREEN : RED }
            ];
        } else {
            return [
                '#' + (i + 1),
                gName,
                { text: eff + '%', color: eff >= 70 ? GREEN : AMBER, bold: true },
                att + '%',
                String(gIds.length)
            ];
        }
    });

    const headers = reportType === 'attendance' 
        ? ['SN', `${viewMode === 'team' ? 'Team' : 'Dept'} Name`, 'Attendance %', 'Late Count', 'Reliability Rank']
        : reportType === 'productivity'
        ? ['SN', `${viewMode === 'team' ? 'Team' : 'Dept'} Name`, 'Productivity %', 'Focus Time', 'Performance Rank']
        : ['SN', `${viewMode === 'team' ? 'Team' : 'Dept'} Name`, 'Productivity %', 'Attendance %', 'Headcount'];

    y = drawSectionHeader(doc, `${viewMode === 'team' ? 'Team' : 'Departmental'} Benchmarking`, y);
    y = drawTable(doc, headers, groupStats, { colW: [0, 30, 210, 320, 430] }, y);

    drawFooter(doc, now.toLocaleString());
    drawSignaturePage(doc, hrUser?.name || 'HR Administrator', now);
    doc.end();

  } catch (err) {
    console.error('HR PDF error:', err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;